# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5faf505c989eeef62fd65f469a89820e4159e7c526169060f6a17b9e6f5eeec7a632e81cfe34f253923f9f648185cbc3166408992a994ac0fb96fb92469dbba

test:
  secret_key_base: 42050c68d65b3cc1b4a83f62708b493ad9742669517c9ade96567c314d087105e6455a730d57ca28fb596172c462d9475c0807e3c4c93cab9bf5e93b82df2c12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
